### ISSUE TITLE
[FEATURE]: Sort and Filter Leaderboard

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#410]
### Feature Summary

- On the leaderboard, the default sort order should be set to AVG CPM descending.  I should see the fastest typers at the top of the list.
- On the leaderboard, please filter out any users who have not completed at least 5 races.
- On the leaderboard, add some type of text that explains "only users who have completed X races will be displayed here"
- Give a badge called "You're In The Club" with description, "you will now show up on the leaderboards" after completing 5 races.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TyrinH** [comment]
I can take care of this

**Comment by webdevcody** [comment]
@TyrinH are you still working on this?

**Comment by TyrinH** [comment]
> @TyrinH are you still working on this?

Yes still on it I have everything done other than the badge, mainly because I am trying to see if I should recreate the badge similar to the first race badge where it has its own component or similar to the first snippet badge where its part of the add snippet action. I'm a little confuse which is the preferable way to make a new badge.
